import type { ClaudeStreamMessage, MessageContentBlock } from '@/types/claudeStream';
import { getMessageContent } from '@/types/claudeStream';

export type TodoStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled';

export interface TodoItem {
  content: string;
  status: TodoStatus;
  activeForm?: string;
}

interface InternalTask {
  toolUseId: string;
  taskId?: string;
  subject: string;
  status: TodoStatus;
  activeForm?: string;
  order: number;
}

// TaskCreate's server-assigned task id reaches the renderer two different
// ways depending on whether the message arrived live or via JSONL replay:
//
//   - LIVE SDK stream: the tool_result block's `content` is the literal
//     string `"Task #<id> created successfully: <subject>"`, generated by
//     the CLI's `mapToolResultToToolResultBlockParam` helper. No envelope
//     metadata. We mirror the CLI's own parsing regex
//     (`/^Task #(\S+) created successfully/`) on that string.
//   - JSONL replay: the CLI persists an additional `toolUseResult` field
//     (camelCase) on the user message envelope carrying the structured
//     `{ task: { id, subject } }` payload. The (unused-in-practice
//     snake_case) `tool_use_result` is accepted defensively for any future
//     SDK that wires the envelope through to live streams.
//
// Both must be recognised so subsequent TaskUpdate(taskId) calls can find
// the row.
const TASK_CREATE_CONTENT_REGEX = /^Task #(\S+) created successfully/;

function extractTaskIdFromContent(content: unknown): string | null {
  const tryMatch = (s: string): string | null => {
    const m = s.match(TASK_CREATE_CONTENT_REGEX);
    return m ? m[1] : null;
  };
  if (typeof content === 'string') return tryMatch(content);
  if (Array.isArray(content)) {
    for (const b of content) {
      if (b && typeof b === 'object' && (b as { type?: unknown }).type === 'text') {
        const text = (b as { text?: unknown }).text;
        if (typeof text === 'string') {
          const id = tryMatch(text);
          if (id) return id;
        }
      }
    }
  }
  return null;
}

function extractTaskIdFromEnvelope(message: unknown): string | null {
  if (!message || typeof message !== 'object') return null;
  const env = message as { tool_use_result?: unknown; toolUseResult?: unknown };
  for (const payload of [env.tool_use_result, env.toolUseResult]) {
    if (!payload || typeof payload !== 'object') continue;
    const task = (payload as { task?: { id?: unknown } }).task;
    if (!task || typeof task !== 'object') continue;
    const id = task.id;
    if (typeof id === 'string' && id.length > 0) return id;
  }
  return null;
}

function coerceSdkStatus(s: unknown): TodoStatus | 'deleted' | null {
  if (s === 'pending' || s === 'in_progress' || s === 'completed') return s;
  if (s === 'deleted') return 'deleted';
  return null;
}

/**
 * Reduce the live message stream into the current todo list under SDK 0.3.x.
 *
 * Where the legacy SDK shipped one snapshot-shaped `TodoWrite` tool_use
 * per turn, the new model drives per-task mutations through discrete
 * `TaskCreate(subject, description, activeForm?)` and
 * `TaskUpdate(taskId, status?, subject?, activeForm?)` tool_use blocks.
 * `TaskCreate`'s server-assigned `task.id` rides back on the corresponding
 * `tool_result`; subsequent `TaskUpdate` calls reference that id.
 *
 * The accumulator keys in-flight rows by `tool_use.id` immediately so the
 * UI can show a freshly-created task before its tool_result arrives, then
 * re-keys to the assigned `task_id` as soon as we see it. `TaskUpdate`
 * with `status: 'deleted'` drops the row entirely.
 */
export function getLatestTodos(messages: ClaudeStreamMessage[]): TodoItem[] | null {
  const byToolUseId = new Map<string, InternalTask>();
  const byTaskId = new Map<string, InternalTask>();
  let order = 0;
  let sawCreate = false;

  for (const m of messages) {
    const content = getMessageContent(m);
    if (!Array.isArray(content)) continue;
    for (const block of content as MessageContentBlock[]) {
      if (!block || typeof block !== 'object') continue;

      if (block.type === 'tool_use') {
        const name = typeof block.name === 'string' ? block.name.toLowerCase() : '';
        const input = block.input;
        if (name === 'taskcreate') {
          if (!block.id) continue;
          sawCreate = true;
          const subject = typeof input.subject === 'string'
            ? input.subject
            : typeof input.description === 'string'
              ? input.description
              : '';
          const task: InternalTask = {
            toolUseId: block.id,
            subject,
            status: 'pending',
            activeForm: typeof input.activeForm === 'string' ? input.activeForm : undefined,
            order: order++,
          };
          byToolUseId.set(block.id, task);
        } else if (name === 'taskupdate') {
          const taskId = typeof input.taskId === 'string' ? input.taskId : undefined;
          if (!taskId) continue;
          const task = byTaskId.get(taskId);
          if (!task) continue;
          const mappedStatus = coerceSdkStatus(input.status);
          if (mappedStatus === 'deleted') {
            byTaskId.delete(taskId);
            byToolUseId.delete(task.toolUseId);
            continue;
          }
          if (mappedStatus) task.status = mappedStatus;
          if (typeof input.subject === 'string') task.subject = input.subject;
          if (typeof input.activeForm === 'string') task.activeForm = input.activeForm;
        }
      } else if (block.type === 'tool_result') {
        const id = block.tool_use_id;
        if (!id) continue;
        const task = byToolUseId.get(id);
        if (!task || task.taskId) continue;
        // Live SDK stream — content string is the only carrier.
        // JSONL replay — both content string AND envelope are present;
        // either resolves to the same id, so we prefer the content path
        // (always present) and fall back to envelope only if the content
        // didn't match (defensive against a future CLI format change).
        const taskId =
          extractTaskIdFromContent(block.content) ??
          extractTaskIdFromEnvelope(m);
        if (taskId) {
          task.taskId = taskId;
          byTaskId.set(taskId, task);
        }
      }
    }
  }

  if (!sawCreate) return null;

  const items: TodoItem[] = [...byToolUseId.values()]
    .sort((a, b) => a.order - b.order)
    .map((t) => {
      const item: TodoItem = { content: t.subject, status: t.status };
      if (t.activeForm) item.activeForm = t.activeForm;
      return item;
    });

  return items.length > 0 ? items : null;
}

export function summarizeTodos(todos: TodoItem[]): {
  done: number;
  total: number;
  running: boolean;
} {
  let done = 0;
  let running = false;
  for (const t of todos) {
    if (t.status === 'completed' || t.status === 'cancelled') done += 1;
    else if (t.status === 'pending' || t.status === 'in_progress') running = true;
  }
  return { done, total: todos.length, running };
}

export function todosKey(todos: TodoItem[] | null): string {
  if (todos === null) return '__null__';
  return JSON.stringify(todos.map((t) => [t.content, t.status]));
}
